name: Android Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for commit messages
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    # Sign release APK (optional - disabled for now)
    #- name: Sign Release APK
    #  uses: r0adkll/sign-android-release@v1
    #  with:
    #    releaseDirectory: app/build/outputs/apk/release
    #    signingKeyBase64: ${{ secrets.SIGNING_KEY }}
    #    alias: ${{ secrets.KEY_ALIAS }}
    #    keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
    #    keyPassword: ${{ secrets.KEY_PASSWORD }}
      
    # Rename the APKs for better identification
    - name: Prepare Release Files
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        mkdir -p release_files
        cp app/build/outputs/apk/debug/app-debug.apk release_files/CosmicCanvas-${{ github.ref_name }}-debug.apk
        cp app/build/outputs/apk/release/app-release-unsigned.apk release_files/CosmicCanvas-${{ github.ref_name }}-release.apk
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 14
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 14

    # Generate changelog from commits since last tag
    - name: Generate Changelog
      id: changelog
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -z "$PREVIOUS_TAG" ]; then
          echo "No previous tag found, including all commits"
          CHANGELOG=$(git log --pretty=format:"- %s (%h)" --reverse)
        else
          echo "Previous tag: $PREVIOUS_TAG"
          CHANGELOG=$(git log ${PREVIOUS_TAG}..HEAD --pretty=format:"- %s (%h)" --reverse)
        fi
        echo "CHANGELOG<<EOF" >> $GITHUB_ENV
        echo "$CHANGELOG" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    # Create release when a tag is pushed
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        body: |
          ## Cosmic Canvas ${{ github.ref_name }}
          
          ### Changes in this release:
          ${{ env.CHANGELOG }}
          
          ### Downloads
          - Debug APK: CosmicCanvas-${{ github.ref_name }}-debug.apk
          - Release APK: CosmicCanvas-${{ github.ref_name }}-release.apk
        files: |
          release_files/CosmicCanvas-${{ github.ref_name }}-debug.apk
          release_files/CosmicCanvas-${{ github.ref_name }}-release.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}