name: Auto Tag and Release

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'LICENSE'

jobs:
  auto-tag-release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for tags and versioning
    
    - name: Get version from build.gradle
      id: get-version
      run: |
        VERSION=$(grep -E "versionName\s*=\s*\"([0-9]+\.[0-9]+\.[0-9]+)\"" app/build.gradle.kts | grep -oE "([0-9]+\.[0-9]+\.[0-9]+)")
        if [ -z "$VERSION" ]; then
          echo "No version found in build.gradle.kts"
          exit 1
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        
    - name: Check if tag exists
      id: check-tag
      run: |
        TAG="v${{ env.VERSION }}"
        if git tag -l "$TAG" | grep -q "$TAG"; then
          echo "Tag $TAG already exists, skipping tagging"
          echo "TAG_EXISTS=true" >> $GITHUB_ENV
        else
          echo "Tag $TAG does not exist, will create it"
          echo "TAG_EXISTS=false" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
        fi
    
    - name: Create and push tag
      if: env.TAG_EXISTS == 'false'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a ${{ env.TAG }} -m "Release ${{ env.VERSION }}"
        git push origin ${{ env.TAG }}
        
    # The android-build.yml workflow will be triggered by the tag push and create the release